import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Tabs } from '../components';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>React Tabs</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Tabs></Tabs>
      </main>
    </div>
  );
}
